### PR TITLE
A much-needed security fix

### PR DESCRIPTION
**Pull request by ian84120**

### CODE REVIEW

**Comment by pantiaq** [comment]
lol dat guys suckin big dix

**Comment by revoxhere** [comment]
Hello, this is duino-coin repository, not furims faucet one - make sure you submit PRs in correct repositories

**Comment by ian84120** [comment]
He does not have a repository for faucet, but I would appreciate it if you could pass this PR on to him for review

**Comment by revoxhere** [comment]
I believe you can contact him on Discord server

**Comment by mgruszkiewicz** [comment]
The faucet repo is located on codeberg.org

https://codeberg.org/Furim/Duco_Faucet_Furime

**Comment by ian84120** [comment]
> The faucet repo is located on codeberg.org
> 
> https://codeberg.org/Furim/Duco_Faucet_Furime

it's probably dead, this repository has far fewer lines, I don't have discord, but I understand people have already passed it on, thanks

**Pull request closed without merging**
