### PR TITLE
Fix some mining key related bugs

### PR DESCRIPTION
**Pull request by Omicron166**
It's annoying when i open the miner and i have to type the mining key None, so here i fix those tiny bugs

### CODE REVIEW

**Comment by revoxhere** [comment]
Could you elaborate the problem? I don't think it's needed

**Comment by Omicron166** [comment]
Well, i mine with the pc miner and i don't have a mining key set. But every time i open the miner, it asks me for the mining key.

Since no one has opened an issue, I took it on my own and i fixed it.

**Comment by revoxhere** [comment]
Could you check if the same thing isn't happening with AVR miner?

**Comment by Omicron166** [comment]
the same code with the same issue, i'm working on it

**Comment by Omicron166** [comment]
Also vs code detects that json itself is not used and someone forget to import random.choice, i'm fixing that

**Comment by Omicron166** [comment]
@revoxhere i have my arduino inside another project, can you test it?

**Pull request merged**
