### PR TITLE
Fix revox's poor coding

### PR DESCRIPTION
**Pull request by DogeRock**
You forgot to import datetime 👍

### CODE REVIEW

**Comment by IdotMaster1** [comment]
LOL

**Comment by IdotMaster1** [comment]
you just added one thing

**Comment by DogeRock** [comment]
Yes, revox forgot to import datetime

**Comment by DogeRock** [comment]
@revoxhere

**Comment by kyngs** [comment]
I do not see why datetime is needed,time seems enough. If revox wanted to merge this reopen it. And please don't use such names.

**Comment by DogeRock** [comment]
datetime is called on line 15. @kyngs Please reopen this.

**Comment by kyngs** [comment]
I ask revox and Bilaboz to review it.

**Pull request merged**
