### PR TITLE
Fixed many grammatical Errors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
maxi trying to become a contributor 2021 colorized :tm:

**Comment by ghost** [comment]
> maxi trying to become a contributor 2021 colorized

Well yes theoretically I am contributing but uh yes

**Comment by revoxhere** [comment]
Thanks for the PR!

**Comment by ghost** [comment]
you did the same to me yesterday

**Comment by ghost** [comment]
> you did the same to me yesterday

h

**Pull request merged**
