### PR TITLE
Added ArduinoJson.h so you dont have to install it manually anymore

### PR DESCRIPTION
**Pull request by BastelPichi**

### CODE REVIEW

**Comment by revoxhere** [comment]
Have you tested it? Shouldnt the .ino code be changed to #include "ArduinoJson.h"?

**Comment by ProtoThis** [comment]
Although this works the preferred way of installing the library (according to there site https://arduinojson.org/v6/doc/installation/) is by using the library manager.

**Comment by ProtoThis** [comment]
> > Although this works the preferred way of installing the library (according to there site https://arduinojson.org/v6/doc/installation/) is by using the library manager.
> 
> yes, but isnt it that for sha1.h too? Either way the Library Manager is always nicer because of automatic updates etc... But since through that getting started is way easyer, i would still do that.

But sha1.h isn't in the repo either is it? It's provider nu the board manager i think.

**Comment by BastelPichi** [comment]
> > > Although this works the preferred way of installing the library (according to there site https://arduinojson.org/v6/doc/installation/) is by using the library manager.
> > 
> > 
> > yes, but isnt it that for sha1.h too? Either way the Library Manager is always nicer because of automatic updates etc... But since through that getting started is way easyer, i would still do that.
> 
> But sha1.h isn't in the repo either is it? It's provider nu the board manager i think.

Its in the arduino code

**Pull request closed without merging**
