### PR TITLE
Update ESP8266_Code.ino

### PR DESCRIPTION
**Pull request by sys-256**
Updated the versions in the ESP8266 code as Primera suggested in the Discord server. Also found out there was a third typo on line 277, so I fixed that one too.

### CODE REVIEW

**Comment by sys-256** [comment]
@revoxhere The code for the arduino due says that it's on version 2.4, the normal arduino is on version 2.53 and the esp32 on version 2.52, should i change those to 2.5 as well?

**Comment by revoxhere** [comment]
Hmm, leave it as 2.53, but corect the 2.52 in one place. Arduino due code can be removed as normal arduino code compiles fine (at least it should)

**Comment by sys-256** [comment]
> Hmm, leave it as 2.53, but correct the 2.52 in one place.

Sorry, I don't really understand it. What should I change to what?

> Arduino code can be removed

You mean the Arduino Due code, right?

**Comment by revoxhere** [comment]
Yes, Due code. ESP code has 2.52 instead of 2.53 in line 218

**Comment by sys-256** [comment]
@revoxhere So I should delete the whole Arduino Due folder, don't change the normal Arduino and ESP32 code, and reverse the changes for the ESP8266, and only change line 218 to 2.53?

**Comment by revoxhere** [comment]
I'll do it

**Pull request merged**
