### PR TITLE
add app.py

### PR DESCRIPTION
**Pull request by lolenseu248**
update for update.sh
add new app.py ( use python3 )

### CODE REVIEW

**Comment by LDarki** [comment]
Hi, for what exactly is the app.py ?
Also, i'll merge the update.sh manually
Ty for the pr

**Comment by lolenseu248** [comment]
The app.py like a monitor for the miners and profile of the user

**Comment by LDarki** [comment]
I can add it at a Tool, but maybe you can improve a little bit the code, for example use loops through the minerlist

**Comment by lolenseu248** [comment]
Screenshot_2022-03-08_21-07-15

**Comment by lolenseu248** [comment]
That is the use app.py

**Comment by LDarki** [comment]
I think that this isn't needed to be in the official github repostory.

If you want make another repostory and i can add the link to the Community-made softwares section.

Ty for the pull-request.
I'll close the pull-request

**Pull request closed without merging**
