### PR TITLE
Added randomization

### PR DESCRIPTION
**Pull request by MrKris7100**
Job randomization, propably faster finding right hash

### CODE REVIEW

**Comment by MrKris7100** [comment]
Tested it a lot, it's not faster 😄

**Comment by MrKris7100** [comment]
Tested it a lot and it's not faster 😄

**Comment by MrKris7100** [comment]
After a few more test, looks like that's a little bit faster

**Comment by revoxhere** [comment]
Implemented in https://github.com/revoxhere/duino-coin/commit/4589f3276fea143068c41d3fa7905e847186efcf

**Pull request closed without merging**
