### PR TITLE
Added Maltese

### PR DESCRIPTION
**Pull request by IdotMaster1**

### CODE REVIEW

**Comment by revoxhere** [comment]
There are some formatting issues (in newlines, mainly), can you fix them?

**Comment by IdotMaster1** [comment]
> There are some formatting issues (in newlines, mainly), can you fix them?

What do you mean?

**Comment by revoxhere** [comment]
`\ n` => `\n` and proper JSON dict entry (end the previous one with `},`)

**Comment by IdotMaster1** [comment]
ah sorry!

**Comment by sys-256** [comment]
@IdotMaster1 You forgot to add a "," at the end of line 761, and a "}," on line 737.

**Pull request merged**
