### PR TITLE
Auto-update feature for AVR and PC miner.

### PR DESCRIPTION
**Pull request by aadek112**
Auto-update function for AVR and PC miner. Can be disabled in miner settings.

### CODE REVIEW

**Comment by revoxhere** [comment]
While it's good for users that use the .py versions, it won't work for .exe users. I'm thinking what would be the easiest way to make it work for them too

**Comment by aadek112** [comment]
What about implementing same thing for downloading exe as for DonateExecutable? Add .exe miner file somewhere in repository(for example in useful-tools branch) and implement same code as for downloading DonateExecutable file?

**Comment by revoxhere** [comment]
Wouldn't downloading the latest release and unzipping it be easier?

**Comment by aadek112** [comment]
You're right. I it will be easier.

**Comment by aadek112** [comment]
Ok. .exe files support added, should work fine.

**Comment by revoxhere** [comment]
Cool, but I'll need a few persons to test it first

**Review by Tech1k — COMMENTED** [review]
This code seems good, but we still need a few people to test it to make sure it'll work as desired in a production environment.

**Comment by Tech1k** [comment]
> This code seems good, but we still need a few people to test it to make sure it'll work as desired in a production environment.

With that being said, if anyone here would like to test it and let us know how testing went, please feel free to do so and we can get this merged once everything works as desired!

**Comment by finnie2006** [comment]
any update?, and is this also a feature possible on esp boards?

**Comment by Weazel486** [comment]
> 

If u made the exe like a virtual machine and had a external file that canbe modded it could work

**Review by abduljana97 — COMMENTED** [review]
save

**Review by abduljana97 — APPROVED** [review]

**Comment by finnie2006** [comment]
Why are you closing this??

**Comment by LDarki** [comment]
Update the miner code then make a new pull-request. Maybe we can merge it.

**Pull request closed without merging**
