### PR TITLE
Added script to upload arduino code without the IDE

### PR DESCRIPTION
**Pull request by hgecode**
Batch script to upload the compiled (hex) file to the Arduino Board without opening the IDE.

### CODE REVIEW

**Comment by connorhess** [comment]
@JoyBed This is your expertise

**Comment by JoyBed** [comment]
This would be a great idea, but if it will be implemented than we need to either write that its just for atmega328p based boards or remake the .bat to take into account also the other AVR arduinos like arduino mega.

**Comment by hgecode** [comment]
Good, just a prompt to select the board, thanks. Which boards we need?

**Comment by JoyBed** [comment]
Basically all that use atmega328p and atmega1280.

**Comment by hgecode** [comment]
And atmega2560?

**Comment by JoyBed** [comment]
Ah yes, that too i forgot about that.

**Pull request merged**
