### PR TITLE
Added new language to PC_miner and fixed a typo in the avr miner

### PR DESCRIPTION
**Pull request by ghost**
Added slovak language to pc miner and also updated the pc miner .py file to work with the new language. Also fixed a little typo in the avr miner.

### CODE REVIEW

**Comment by lghustle** [comment]
ATTENTION ADMIN.

REMOVE ME FROM THESE THREADS!!!!!

THe unsubscribe button DOES NOT WORK!!!

I will reply all until removed!

**Comment by lghustle** [comment]
ATTENTION ADMIN.

REMOVE ME FROM THESE THREADS!!!!!

THe unsubscribe button DOES NOT WORK!!!

I will reply all until removed!  

L.G.

**Comment by ghost** [comment]
^^^^ updated README_sk_SK.md with the nonceminer ban, and added the warning to not use it

**Comment by revoxhere** [comment]
Nice job. What's your username?

**Comment by ghost** [comment]
Thanks, Its backo, but I dont need a reward, im just doing it to help out translate :)

**Pull request merged**
