### PR TITLE
Adding unofficial miner: ESPython Miner

### PR DESCRIPTION
**Pull request by fabiopolancoe**
¿Are you tired of  AVR miners not working? ¿Do you want to mine at night without leaving your PC turned on? ¿Would you like to try mining with ESP devices while keeping the MicroPython firmware in it?

We have the solution: ESPython Miner
A standalone miner for ESP8266/ESP32 devices running MicroPython firmware, it's almost entirely based on the official PC_Miner's code, but adapted to run on this devices without needing to be connected to a computer while mining.

You could copy and paste the code line by line into the Micropython's REPL, but it's obviously better to upload the code to the board, to do that, you can use Thonny Python IDE: Download the ESPythonMiner.py, open it with Thonny, edit the settings, connect your board and upload the code, you'll see the device starting to mine DUCO.

Technical note: Python is obviously much slower than compiled C++ code, that's why this miner uses AVR difficulty instead of ESP32, but this can be changed without problem.

Hope you enjoy it! 👍🏼

### CODE REVIEW

**Review by fabiopolancoe — COMMENTED** [review]
A little change
EDIT: Wait, what is this? Never mind lol

**Comment by revoxhere** [comment]
Good work, but could you make a separate repository for it and then I'd link it in the README? I think it'd be better than adding yet another miner to the master branch.

**Comment by fabiopolancoe** [comment]
> Good work, but could you make a separate repository for it and then I'd link it in the README? I think it'd be better than adding yet another miner to the master branch.

Sure, I will, thanks

**Comment by fabiopolancoe** [comment]
Done! https://github.com/fabiopolancoe/ESPython-DUCO-Miner

**Comment by revoxhere** [comment]
Added in https://github.com/revoxhere/duino-coin/commit/d88d528a84c41eb40b2c7432d8e7d4a54d92fa36

**Pull request closed without merging**
