### PR TITLE
Added Vietnamese translation

### PR DESCRIPTION
**Pull request by MinatoIsuki**
What I've done:
- Added Vietnamese to AVR_Miner, CLI_Wallet, PC_Miner, Wallet and Readme.
I'm just a beginner at Github and coding so if there's any mistake, please let me know!

### CODE REVIEW

**Comment by Tech1k** [comment]
Hello @JustSomeRandomGuy3!

Welcome to Github and thank you for contributing to the Duino-Coin project! Your changes look good, but could you squash your commits into a single one? Here is a fairly easy tutorial on how to do that: https://www.git-tower.com/learn/git/faq/git-squash

Let me know if you have any questions!

**Review by Tech1k — CHANGES_REQUESTED** [review]
Hello @JustSomeRandomGuy3!

Welcome to Github and thank you for contributing to the Duino-Coin project! Your changes look good, but could you squash your commits into a single one? Here is a fairly easy tutorial on how to do that: https://www.git-tower.com/learn/git/faq/git-squash

Let me know if you have any questions!

**Comment by MinatoIsuki** [comment]
Hello @Tech1k,

Thank you for viewing my PR, but, after I read the website, should I...

1. Close this PR and an administrator will squash and merge it

Or...

2. Just squash it from Github Desktop (I'm currently  away from my laptop)

To squash all commit to one? I'm just a beginner and this is my first PR so I don't have any idea how this works yet. If there is another way, please let me know!

EDIT: Forget it.

**Comment by MinatoIsuki** [comment]
That should do the job.

**Comment by Tech1k** [comment]
It seems that I might be able to merge this pr while squashing all the commits on my side, let me check.

**Review by Tech1k — APPROVED** [review]

**Comment by Tech1k** [comment]
Thank you for your contribution to Duino-Coin!

**Pull request merged**
