### PR TITLE
ESP8266: Use strtok for parsing incoming job

### PR DESCRIPTION
**Pull request by snakeye**

### CODE REVIEW

**Comment by revoxhere** [comment]
What does that even PR do? Any details would be welcome.

**Comment by snakeye** [comment]
Yes, my bad. I had to provide more context.

The function `strtok` is the standard way to separate the string by some delimiter. It makes sense to use it instead of custom implementation.

**Review by revoxhere — APPROVED** [review]
LGTM

**Comment by revoxhere** [comment]
Thanks for your input.

**Pull request merged**
