### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by IdotMaster1**
Added rss feed and "(mostly)"

### CODE REVIEW

**Comment by Bilaboz** [comment]
Mostly ins't necessary

**Comment by IdotMaster1** [comment]
wow

**Comment by IdotMaster1** [comment]
i spent time making it

**Comment by IdotMaster1** [comment]
and its better then a illegal newsletter

**Comment by kyngs** [comment]
I do not see reason for this to exists, we already have an announcement channel on discord.

**Comment by Bilaboz** [comment]
I mean the word "mostly" isn't necessary
and making a rss feed is simple

**Comment by IdotMaster1** [comment]
so you dont care?

**Comment by IdotMaster1** [comment]
wait, i am goona add somethings to RSS

**Comment by ghost** [comment]
> I do not see reason for this to exists, we already have an announcement channel on discord.

Maybe a person doesn't want to create a Discord Account?
Maybe they have privacy concerns?

**Comment by kyngs** [comment]
I would have more privacy concerns with duino than with discord.

**Comment by ghost** [comment]
OK that's true but, still

**Comment by kyngs** [comment]
I will leave this to revox.

**Comment by Bilaboz** [comment]
We will see that later

**Pull request closed without merging**
