### PR TITLE
Add A Easy To Use Raspberry Pi Install Script

### PR DESCRIPTION
**Pull request by Grantrocks**
I created a simple install script under tools to install Duino Coin on the Raspberry Pi. It downloads the repository then it adds some shortcuts in the menu under utilities for easy use. It uses icons from the resources directory. In the future i will have it do some more things.
Things i might make it do in the future is make a folder name duino coin in the app launcher with all of the apps inside of it.
I really like this project and I would really like to contribute to it. I have many ideas for this tool and I will spend some time to make them.

### CODE REVIEW

**Comment by LDarki** [comment]
Hi, we need that at least 3 users test this code and if it works fine maybe we merge it to main

**Comment by Grantrocks** [comment]
Ok. Do you want me to test it 3 times or 3 different people?

**Comment by LDarki** [comment]
3 different people. The thing is that i don`t have any raspberry here to test it.

**Comment by Grantrocks** [comment]
Let me see if anyone in the raspberry pi forums would help.

**Comment by Grantrocks** [comment]
Just gonna says this real quick. Small typo in cli wallet. When the users enters help the donation string has the typo developpers instead of developers.

**Comment by Grantrocks** [comment]
I have tested the program and it works. Tested it multiple times each time ended with success. Each test made a shortcut in the utility menu

**Comment by GameOneDev** [comment]
This is made for the desktop version of Raspbian.

**Comment by Grantrocks** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GameOneDev** [comment]
I can test, but i have "CLI" version of Raspbian and i don't need shortcut on the desktop(So it would be good if you split the versions for different systems)(sorry for my English)

**Comment by Grantrocks** [comment]
you can see the shortcuts in the cli
cd /home/pi/.local/share/applications
ls
then look for the names something like duino-coin-avr.desktop
i can also send a screenshot

**Comment by Grantrocks** [comment]
[Video Evidence Of Script Working](https://1drv.ms/v/s!Al4PNW10L-97n0kVjk_SbOY6rR-z?e=kyGhwi)
Screenshot:
2022-02-11-173032_1600x900_scrot

**Comment by LDarki** [comment]
Hi, if you can beautify the code a little bit i`ll merge it

**Comment by LDarki** [comment]
Ty, i`ll merge it manually.

**Pull request closed without merging**
