### PR TITLE
Add Czech translation of README - README_cz_CZ.md

### PR DESCRIPTION
**Pull request by fpetru104**

### CODE REVIEW

**Comment by LDarki** [comment]
Hi, why you removed the Slovakia readme?

**Comment by fpetru104** [comment]
> Hi, why you removed the Slovakia readme?

Oops, I used it as an template. I didn't mean to remove it.. Is it possible to take it back?

**Comment by LDarki** [comment]
I can add the file manually and remove this pull-request if you want.

**Comment by fpetru104** [comment]
> I can add the file manually and remove this pull-request if you want.

I would appreciate that. Thank you

**Comment by LDarki** [comment]
Done, 
Ty for the translation.
i`ll close this pull-request.

**Pull request closed without merging**
