### PR TITLE
ESP-8266 improved performance (#1580 continuation)

### PR DESCRIPTION
**Pull request by matteocrippa**
I was reading #1580 and I gave a try to improve performances for the ESP8266, the idea come from using an internal (dogecoin inspired) sha1 algorithm and a bit of loop unrolling, plus including the findings of #1580 that looked very promising.

So far a D1 Mini managed to reach up to 65 kH/s.

The issue is that the RIG is not listed in the miners, I guess due to the difficulty dance and checks.

I was wondering if @revoxhere you can introduce a new START_DIFF value with a different naming (eg. "ESP8266NHV2"? ) with around 5000k of difficulty, so far seems the most promising according the logs below.

🚨 🚨 🚨   One note, don't use this code till the change in difficulty is in place or mining will not be counted.

```log
Fetching mining node from the poolpicker in 1s
Poolpicker selected the best mining node: coffee-pool-1


Connecting to the Duino-Coin server...
Connected to the server. Server version: 3.0

Asking for a new job for user: xxxxx
Received job with size of e4081fe83cf7e174a5082c0c599e298e94e42465,6ab359908751470a4f06e109a7ad75dd37c4449b,3000
Parsed job: e4081fe83cf7e174a5082c0c599e298e94e42465 6ab359908751470a4f06e109a7ad75dd37c4449b 300001
BAD,Too low starting difficulty share #1 (84077) hashrate: 65.07 kH/s (1.29s)

Asking for a new job for user: xxxxx
Received job with size of 7aa2cfdaf20056064e4fec2fdc52e1f05f694d0d,2f7085634016315137f98d74f06ddba14a4cf220,1300
Parsed job: 7aa2cfdaf20056064e4fec2fdc52e1f05f694d0d 2f7085634016315137f98d74f06ddba14a4cf220 130001
BAD,Too low starting difficulty share #2 (6158) hashrate: 65.92 kH/s (0.09s)

Asking for a new job for user: xxxxx
Received job with size of d0c5b275aae878495cc87dd9c3914597669bcec3,128fe86a677b308d069134abe70ba51e39489178,49848
Parsed job: d0c5b275aae878495cc87dd9c3914597669bcec3 128fe86a677b308d069134abe70ba51e39489178 4984801
GOOD share #3 (933619) hashrate: 65.51 kH/s (14.25s)

Asking for a new job for user: xxxxx
Received job with size of a9083c1e0876c3fdc0f6a17bc585a6d1eeeb019e,8c2f32a506c917c67b2fd75323238829a83f3e26,14365
Parsed job: a9083c1e0876c3fdc0f6a17bc585a6d1eeeb019e 8c2f32a506c917c67b2fd75323238829a83f3e26 1436501
GOOD share #4 (1175715) hashrate: 65.60 kH/s (17.92s)

Asking for a new job for user: xxxxx
Received job with size of 177c5ae9b0a1f9cf4b8d8013522ac6869c26766a,9c9d52cc4d4939aa0dedd9eba84de8571b23b65a,5190
Parsed job: 177c5ae9b0a1f9cf4b8d8013522ac6869c26766a 9c9d52cc4d4939aa0dedd9eba84de8571b23b65a 519001
GOOD share #5 (420963) hashrate: 65.55 kH/s (6.42s)

Asking for a new job for user: xxxxx
Received job with size of 727d14d1a5be989ece2ac05ad0d34e161bb50468,ccaab86f8ea69736dab3615ea60aa8363d2af62f,33935
Parsed job: 727d14d1a5be989ece2ac05ad0d34e161bb50468 ccaab86f8ea69736dab3615ea60aa8363d2af62f 3393501
GOOD share #6 (2233081) hashrate: 65.48 kH/s (34.10s)

Asking for a new job for user: xxxxx
Received job with size of 23d33e944efb435dff32632378339ff696732aee,656565e81d016d2d5eca2a4fc980e7018cefd5a4,6597
Parsed job: 23d33e944efb435dff32632378339ff696732aee 656565e81d016d2d5eca2a4fc980e7018cefd5a4 659701
GOOD share #7 (636619) hashrate: 65.56 kH/s (9.71s)

Asking for a new job for user: xxxxx
Received job with size of a4e408f522354402d1d3ecae6d2cbb61059e206e,f50a4d8bcca28bbd4e04a3e05ab3053f9875fd3e,25000
Parsed job: a4e408f522354402d1d3ecae6d2cbb61059e206e f50a4d8bcca28bbd4e04a3e05ab3053f9875fd3e 2500001
GOOD share #8 (347088) hashrate: 65.54 kH/s (5.30s)

Asking for a new job for user: xxxxx
Received job with size of 2af696089894f358b15d16b4d3693f51c5f5f8a9,3f0673c132019de5da824a6c0563a9d2a418385f,36752
Parsed job: 2af696089894f358b15d16b4d3693f51c5f5f8a9 3f0673c132019de5da824a6c0563a9d2a418385f 3675201
GOOD share #9 (86411) hashrate: 65.33 kH/s (1.32s)

Asking for a new job for user: xxxxx
Received job with size of c2d073e5ba1da8084f67b616e14dc223f40774fd,ea9d1aa249929c7b385821cb1bf8d1cc32e255e2,46682
Parsed job: c2d073e5ba1da8084f67b616e14dc223f40774fd ea9d1aa249929c7b385821cb1bf8d1cc32e255e2 4668201
```

### CODE REVIEW

**Comment by revoxhere** [comment]
Thanks for your work. Please try `ESP8266H`, I've made the necessary changes and tested this on my board.

**Comment by matteocrippa** [comment]
@revoxhere I can see now the miner listed properly, but I see the hashrate has a warning

Screenshot 2023-11-12 at 17 13 41

**Comment by matteocrippa** [comment]
Screenshot 2023-11-13 at 22 01 01

I think now is working fine @revoxhere 

Probably we will need to consider something similar for ESP32, an ESP32H any soon

**Comment by revoxhere** [comment]
@matteocrippa what's the current status of ESP32 performance? I've been off for about a month or so and I've fallen out of rhytm. If there is any work being done for 32 too then I'm happy to change the difficulty tiers before drafting a new release.

**Comment by matteocrippa** [comment]
@revoxhere I think we need to tweak a bit ESP8266 first, I see we can make it work up to 65 kH/s so I guess you will need to refine a bit the values.
Then I have a local branch where I merged ESP8266 and ESP32 (with support for WROOM, S3, C3, S2) but needs more testing and debugging. Also I skip, by purpose, any spport for MQTT and Webserver there, so it's a huge refactor.
Plan is: let's address this PR first than we work on the other, sounds like a plan?

**Comment by revoxhere** [comment]
The `ESP8266H` ("old" difficulty) has been updated and it should be good to go up to around 75kh/s although I'm not sure where I left off and if the pools already have the change to respect this change. Later I'll try to find my ESP8266 board to check it myself.
`ESP32` difficulty updated to 37kh/s (per core).

**Comment by revoxhere** [comment]
Added in 98cb6bf3ee64

**Pull request closed without merging**
