### PR TITLE
Added Italian language

### PR DESCRIPTION
**Pull request by ste-t**
I've added Italian language to the AVR Miner, the PC Miner and the Wallet.
I'm happy to contribute to this project :D

### CODE REVIEW

**Comment by sys-256** [comment]
Minor "bug": You forgot to rename "english" to "italian" in the wallet_langs.json, as you see in the failed check results. Make a comment when you fixed it, and @revoxhere will probably merge it.

Anyways, thanks for your contribution!

**Comment by ste-t** [comment]
> Minor "bug": You forgot to rename "english" to "italian" in the wallet_langs.json, as you see in the failed check results. Make a comment when you fixed it, and @revoxhere will probably merge it.
> 
> Anyways, thanks for your contribution!

Oh, lol. Thanks.
Btw I've talked directly to revox and he told me he will merge it

**Comment by ste-t** [comment]
Done

**Comment by revoxhere** [comment]
Thanks for the PR!

**Pull request merged**
