### PR TITLE
Database conversion

### PR DESCRIPTION
**Pull request by connorhess**
replaced transactions txt with database
i will also make it store the userdata on its own table in the database just need to find that part and understand it first

### CODE REVIEW

**Comment by IdotMaster1** [comment]
this is cool

**Comment by IdotMaster1** [comment]
revox, approve this or i come to your house and steal your internet

**Comment by Bilaboz** [comment]
c isn't defined at line 482
same for conn at 483

**Comment by connorhess** [comment]
is that the reset part? let me fix
forgot about that one

**Comment by connorhess** [comment]
i also need to update the 'open transactions' page

**Comment by connorhess** [comment]
just wait before merge

**Comment by IdotMaster1** [comment]
c o o l

**Comment by revoxhere** [comment]
Hmmm, is this happening just for me?
I see the database is working good though

**Comment by connorhess** [comment]
What page is that?

**Comment by revoxhere** [comment]
Main wallet window

**Comment by connorhess** [comment]
will check on my pc when i am by my laptop

**Comment by connorhess** [comment]
i dont get that. it works perfectly for me

**Comment by revoxhere** [comment]
Ok, let me investigate myself and also I'll check on Windows

**Comment by connorhess** [comment]
yeah might be linux

**Comment by connorhess** [comment]
image

**Comment by revoxhere** [comment]
Closing as it's already merged in 1.7

**Pull request closed without merging**
