### PR TITLE
Update project maintainer email address

### PR DESCRIPTION
**Pull request by Tech1k**

### CODE REVIEW

**Review by revoxhere — APPROVED** [review]

**Comment by revoxhere** [comment]
@Tech1k ⚔️

**Comment by Tech1k** [comment]
> @Tech1k ⚔️

⚔️

**Comment by revoxhere** [comment]
> > @Tech1k ⚔️
> 
> ⚔️

image
xD this was meant to symbolize a branch conflict

**Comment by Tech1k** [comment]
Merge conflicts fixed and once again, the programmer is victorious ⚔️🏆

**Pull request merged**
